name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        c_compiler: [gcc]
        cpp_compiler: [g++]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxrandr-dev libx11-dev libxext-dev libxrender-dev libxi-dev \
          libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Collect executable and assets
      run: |
        mkdir -p output
        cp build/10SecondIntern output/
        cp -r build/assets output/
        ls -alh output/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: output/

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

  build-macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        c_compiler: [clang]
        cpp_compiler: [clang++]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install cmake
        brew install glfw

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Collect executable and assets
      run: |
        mkdir -p output
        cp build/10SecondIntern output/
        cp -r build/assets output/
        ls -alh output/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: output/

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

  build-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        c_compiler: [gcc]
        cpp_compiler: [g++]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MinGW (GCC/G++)
      run: |
        choco install mingw -y  # Install MinGW for GCC/G++ on Windows
        echo "Adding MinGW to PATH"
        setx PATH "%PATH%;C:\ProgramData\mingw64\mingw32\bin;C:\ProgramData\mingw64\mingw64\bin"  # Manually add MinGW to PATH

    - name: Wait for environment to refresh
      run: |
        sleep 10

    - name: Install CMake
      run: |
        choco install cmake -y  # Install CMake using Chocolatey
      
    - name: Install GLFW
      run: choco install glfw --pre -y
      
    - name: Install Freetype
      run: choco install freetype --pre -y
      
    - name: Install Libsndfile
      run: choco install libsndfile -y
        
    - name: Install SDL2 manually
      run: |
        Invoke-WebRequest -Uri "https://www.libsdl.org/release/SDL2-2.26.5-win64-x64.zip" -OutFile "SDL2.zip"
        Expand-Archive -Path "SDL2.zip" -DestinationPath "C:\libsdl2"
        echo "C:\libsdl2\bin" | setx PATH "%PATH%"
  
    - name: Wait for environment to refresh
      run: |
        # Adding a small wait time to ensure the environment is refreshed
        sleep 10  # This can be adjusted as needed
  
    - name: Create build directory
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles"  # Use MinGW Makefiles generator for CMake
  
    - name: Build the project
      run: |
        cd build
        mingw32-make  # Use mingw32-make to build the project
        
    - name: Collect executable and assets
      run: |
        mkdir -p output
        cp build/10SecondIntern.exe output/
        cp -r build/assets output/
        ls -alh output/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: output/

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
